### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by pranshuchittora** [pranshuchittora/autarky#1]
Roadmap :arrow_down: 
Visit : https://github.com/pranshuchittora/autarky/projects/1

**Comment by pranshuchittora** [comment]
### v1.2
- [ ] Migrate from `Prompts` to `Inquirer`
- [ ] Show node_modules size & total size deleted.
- [ ] Write tests
- [ ] Add progress loader/spinner
